import React, { useEffect, useState } from 'react';
import { History, Play, Sparkles, Clock, Lock } from 'lucide-react';
import { RecentTopic, Topic } from '../types';
import { api } from '../lib/api';
import { useAuth } from '../context/AuthContext';

interface RecentTopicsViewProps {
  onSelectTopicToPractice: (topic: Partial<Topic>) => void;
}

export function RecentTopicsView({ onSelectTopicToPractice }: RecentTopicsViewProps) {
  const { user, openAuthModal } = useAuth();
  const [recentTopics, setRecentTopics] = useState<RecentTopic[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    if (!user) {
      setRecentTopics([]);
      return;
    }

    let isMounted = true;
    setIsLoading(true);
    api
      .getRecentTopics()
      .then((res) => {
        if (isMounted) {
          setRecentTopics(res.recentTopics);
        }
      })
      .catch((err) => {
        console.error('Failed to load recent topics:', err);
      })
      .finally(() => {
        if (isMounted) setIsLoading(false);
      });

    return () => {
      isMounted = false;
    };
  }, [user]);

  const formatDate = (isoStr: string) => {
    try {
      const d = new Date(isoStr);
      return d.toLocaleDateString(undefined, {
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      });
    } catch {
      return '';
    }
  };

  if (!user) {
    return (
      <div className="w-full max-w-xl mx-auto text-center py-16 px-6 bg-white dark:bg-[#201C19] border border-gray-100 dark:border-stone-800/80 rounded-3xl shadow-[0_4px_20px_rgba(0,0,0,0.03)]">
        <div className="w-14 h-14 rounded-2xl bg-[#FFF5ED] dark:bg-[#F27D26]/20 text-[#F27D26] mx-auto flex items-center justify-center mb-4">
          <Lock className="w-7 h-7" />
        </div>
        <h3 className="text-xl font-bold text-[#2D2926] dark:text-[#F5F5F4] font-['Space_Grotesk'] mb-2">
          Account-Specific Practice Log
        </h3>
        <p className="text-xs sm:text-sm text-stone-500 dark:text-stone-400 max-w-sm mx-auto mb-6">
          Sign in to save and practice your generated topics across all your sessions.
        </p>
        <button
          id="sign-in-for-recent-btn"
          onClick={() => openAuthModal('login')}
          className="px-6 py-3 rounded-2xl bg-[#F27D26] hover:bg-[#D96A1C] text-white text-xs sm:text-sm font-bold shadow-lg shadow-[#F27D26]/20 cursor-pointer"
        >
          Sign In / Create Account
        </button>
      </div>
    );
  }

  return (
    <div className="w-full max-w-5xl mx-auto space-y-6">
      
      {/* Header Bento Tile */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-gray-100 dark:border-stone-800/80">
        <div>
          <span className="text-[11px] font-extrabold uppercase tracking-widest text-[#F27D26]">
            History Log
          </span>
          <h2 className="text-2xl sm:text-3xl font-bold text-[#2D2926] dark:text-[#F5F5F4] font-['Space_Grotesk'] mt-1">
            Recent Topics
          </h2>
          <p className="text-xs text-stone-500 dark:text-stone-400 mt-0.5">
            Topics generated by <span className="font-semibold text-stone-700 dark:text-stone-300">{user.displayName}</span>
          </p>
        </div>
        <span className="self-start sm:self-auto text-xs font-bold px-3 py-1.5 rounded-xl bg-stone-100 dark:bg-stone-800 text-stone-600 dark:text-stone-300">
          {recentTopics.length} generated topics
        </span>
      </div>

      {isLoading ? (
        <div className="text-center py-16 text-stone-400 text-sm font-medium">
          Loading your recent topics...
        </div>
      ) : recentTopics.length === 0 ? (
        <div className="bg-white dark:bg-[#201C19] border border-gray-100 dark:border-stone-800/80 rounded-3xl p-10 text-center shadow-[0_4px_20px_rgba(0,0,0,0.03)]">
          <History className="w-10 h-10 text-stone-300 dark:text-stone-600 mx-auto mb-3" />
          <p className="text-base font-bold text-[#2D2926] dark:text-[#F5F5F4] mb-1 font-['Space_Grotesk']">
            No topics generated yet
          </p>
          <p className="text-xs text-stone-500 dark:text-stone-400 max-w-sm mx-auto">
            When you click "Generate Topic", your prompt will automatically be recorded here for quick replay.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
          {recentTopics.map((item) => (
            <div
              key={item.id}
              className="bg-white dark:bg-[#201C19] border border-gray-100 dark:border-stone-800/80 rounded-2xl p-5 flex items-center justify-between gap-4 shadow-[0_4px_20px_rgba(0,0,0,0.03)] hover:border-[#F27D26]/40 transition-all group"
            >
              <div className="space-y-1.5 min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <span className="px-2.5 py-0.5 rounded-lg text-[10px] font-bold uppercase bg-[#FFF5ED] dark:bg-[#F27D26]/20 text-[#F27D26]">
                    {item.category}
                  </span>
                  <span className="text-[11px] text-stone-400 flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    {formatDate(item.generatedAt)}
                  </span>
                </div>
                <h4 className="text-sm sm:text-base font-bold text-[#2D2926] dark:text-[#F5F5F4] leading-snug truncate group-hover:text-[#F27D26] transition-colors">
                  {item.topicTitle}
                </h4>
              </div>

              <button
                id={`practice-recent-${item.id}`}
                onClick={() =>
                  onSelectTopicToPractice({
                    id: item.topicId,
                    title: item.topicTitle,
                    category: item.category as any,
                  })
                }
                className="px-3.5 py-2 rounded-xl bg-[#FFF5ED] dark:bg-[#F27D26]/20 text-[#F27D26] hover:bg-[#F27D26] hover:text-white text-xs font-bold flex items-center gap-1.5 shrink-0 transition-all cursor-pointer shadow-xs"
              >
                <Play className="w-3 h-3 fill-current" />
                <span>Speak</span>
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
